language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
# command to run tests
script:
  - pytest
