version: 2

jobs:
  build:  
    working_directory: ~/weekly-menu
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/mongo:4.2
    steps:
      - checkout
      - run:
          command: | 
            sudo pip install pipenv
            pipenv install
            sudo pip install -r requirements.txt
            pytest